int questao1(int num);
int questao2(int num);
int questao3(int num);
int questao4(int *vetor, int tamanho);
int questao5(int num);
int questao6(int k, int n);
void questao7(int *vetor, int contador);
int questao8(int num1, int num2);
int questao10(int num, int numBusca, int *numOcorrencias);
int questao11(int multiplicando, int multiplicador) ;
void questao12(int num);
void questao13(int num);
void questao14(int num);
void questao15(int num);
int questao16(int num);

void testeQ1();
void testeQ2();
void testeQ3();
void testeQ4();
void testeQ5();
void testeQ6();
void testeQ7();
void testeQ8();
void testeQ10();
void testeQ11();
void testeQ12();
void testeQ13();
void testeQ14();
void testeQ15();
void testeQ16();